In [16]:
import os
import wrf
import math
import cmaps
import datetime
import numpy as np
import netCDF4 as nc

In [23]:
def read_decoded_dat(pawr):
    dtype=np.dtype('>f') ### big endian float
    # dtype=np.dtype('<f') ### little endian float

    vread=np.fromfile(pawr,dtype=dtype)

    vlon_radar=vread[1]
    vlat_radar=vread[4]
    vz_radar=vread[7]
    print('==============================')
    print('[pawr radar info]')
    print('radar_site_lon: ',vlon_radar)
    print('radar_site_lat: ',vlat_radar)
    print('radar_site_hgt: ',vz_radar)

    nrec=7     # nrec=8 ### radar-4d
    ioffset=9

    ndata=int((len(vread)-ioffset)/(nrec+2))
    print('radar_data_num: ',ndata)

    vdata=np.zeros(shape=(ndata,nrec))

    for i in range(ndata):
        ista=i*(nrec+2)+1+ioffset
        iend=i*(nrec+2)+nrec+1+ioffset
        vdata[i,:]=vread[ista:iend]

    print('------------------------------')
    print('pawr[*,0] = obs variable')
    print('pawr[*,1] = longitude')
    print('pawr[*,2] = latitude')
    print('pawr[*,3] = altitude')
    print('pawr[*,4] = obs value')
    print('pawr[*,5] = obs error std')
    print('pawr[*,6] = obs type')
    print('==============================')

    return vdata

def read_wrf_latlon(ifile):
 
    ncObj = Dataset(ifile,'r',format='NETCDF3_CLASSIC')

    lat = ncObj.variables['XLAT_M'][:]
    lon = ncObj.variables['XLONG_M'][:]

    ncObj.close()
    return  lat, lon    lat1,lon1 = read_wrf_latlon("/public/home/premopr/data/SWAN_radar_process/GEJBGD/cappi_to_wrf/geo_em.d04.nc" )
    nlat = np.shape(lat1)
    nlon = np.shape(lon1)

    new_cappi = np.zeros((21, nlat[1], nlat[2])
    maxdbz = np.zeros((nlat[1], nlat[2])cd

In [59]:
mask = '/data/ra000007/zhaoyang/postprocess/jp_pawr/data/GEJPTK_cappi_d04_mask.nc'
pawr = '/data/ra000007/zhaoyang/postprocess/jp_pawr/data/pawr/radar_20210730060100.dat'

pawr = read_decoded_dat(pawr)
fillvalue = 1
pawr[:,4][pawr[:,4] < 1] = fillvalue
pawr[:,4] = [10 * np.log10(num) for num in pawr[:,4]]


lat1,lon1 = read_wrf_latlon("/public/home/premopr/data/SWAN_radar_process/GEJBGD/cappi_to_wrf/geo_em.d04.nc")
nlat = np.shape(lat1)
nlon = np.shape(lon1)

new_cappi = np.zeros((21, nlat[1], nlat[2]))
maxdbz = np.zeros((nlat[1], nlat[2]))



mask = nc.Dataset(mask) 
lat = mask.variables['lat']
lon = mask.variables['lon']
cappi = np.zeros_like(mask.variables['dbz'])

lev = np.array([500,1000,1500,2000,2500,3000,3500,4000,4500,5000,5500,6000,7000,8000,9000,10000,12000,14000,15500,17000,19000])







[pawr radar info]
radar_site_lon:  139.60898
radar_site_lat:  35.8615
radar_site_hgt:  29.3
radar_data_num:  833616
------------------------------
pawr[*,0] = obs variable
pawr[*,1] = longitude
pawr[*,2] = latitude
pawr[*,3] = altitude
pawr[*,4] = obs value
pawr[*,5] = obs error std
pawr[*,6] = obs type
[[[[0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   ...
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]]

  [[0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   ...
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]]

  [[0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   ...
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]]

  ...

  [[0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   ...
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]]

  [[0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   ...
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]]

  [[0 0 0 ...